name: Daily job

on:
  schedule:
    # 05:00 UTC ≈ 07:00 in NL (CET/CEST afhankelijk). Pas aan naar wens.
    - cron: "0 5 * * *"
  workflow_dispatch: {}   # handmatige run-knop

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # nodig voor commit/push
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Installeer dependencies indien je requirements.txt hebt
      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python scripts/run_job.py

      - name: Commit site output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add site
          git commit -m "Update site $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes to commit"
          git push
