name: Daily job

on:
  schedule:
    - cron: "0 5 * * *"   # 05:00 UTC ≈ 07:00 NL (zomer)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run script (schrijft naar ./docs)
        run: |
          python daily_export.py || true
          # of: python scripts/run_job.py

      - name: Commit docs output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
